---

- hosts: ansible
  tasks:
    - name: Clone roles in the ansible playbook
      git:
        repo: "https://github.com/tovletoglou/{{ item }}.git"
        dest: "/home/vagrant/ansible-playbook-elastic-cluster/roles/{{ item }}"
      with_items:
        - ansible-role-dotfiles
        - ansible-role-firewalld
        - ansible-role-git
        - ansible-role-initialize
        - ansible-role-user
        - ansible-role-yum-repos
